In [55]:
import pandas as pd

In [56]:
df = pd.read_csv("./commit_info_2025.csv")

C:\Users\nopes\AppData\Local\Temp\ipykernel_9248\1833696204.py:1: DtypeWarning: Columns (2,4,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("./commit_info_2025.csv")

In [57]:
df = df.drop(0) #get rid of numbers to make sure csv was read correctly
print(df.shape)
df

(6198, 396)

,ID,Project_Name,Author_ID,Created,Nr_Files,Tracking_ID,files,Commit Message;;;;;,Unnamed: 8,Unnamed: 9,...,Unnamed: 386,Unnamed: 387,Unnamed: 388,Unnamed: 389,Unnamed: 390,Unnamed: 391,Unnamed: 392,Unnamed: 393,Unnamed: 394,Unnamed: 395
1,I0016c57575eda0c77b49ae577d2a322103d80d03,cat/tapas/cfg/rmca,1069329,41:01.0,1,JIRA-ID: BSS_CHA-23938,['config/host-config.json'],Add new network to RMCA WM cluster 1 Accident...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"I001768f8d53c879f8c826e98d24b0130eef344f1,rmca...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I0052410028ad8ea53a8b2e4e2e8584391e03927a,rmca/com.ericsson.bss.rmca.cus.packaging.msv,9381,37:55.0,1,SCM,['bom/pom.xml'],Set snapshot version RMCA CUS - 2.80.3-SNAPSH...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I0056c24118b756ee9463dfbbe69f5ddfbeb02c05,charging/com.ericsson.bss.rm.coba.gui,9255,12:25.0,1,TEST,['ui/src/coba/components/globallist-specificat...,Fix invalid HTML Incorrect matching parenthes...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"I006526646bde76663d20e9944cb85c0c0307b4fc,rmca...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6194,"Iffcac18d598dc694e19b0e0d3933747a5ae816a4,rmca...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6195,"Iffd80a804135253ae45cd2f8865491f57dd547c2,rmca...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6196,"Iffe7fae3598358e3b9bdb740a972f154f638609b,rmca...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6197,"Ifff275a1012ba92bbbb00e6214c64d6f9fbc30a1,rmca...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6198,Ifff842b14e7d184150a308cc18eeeabe9789ab36,bssf/rmca/cn/com.ericsson.bss.rmca.config,1075848.0,08:20.0,1.0,SCM,['bom/pom.xml'],Step RMCA Version RMCA 24.246.2 Tracking-Id:...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [457]:
def handle_normal_row(row):
    pr = row[0]
    author = row[2]
    file = clean_file(row[6])
    title = clean_title(row[7])
    body = 'nan'
    
    if (len(file) == 0):
        return []
    else:
        return [pr, ';', file, ';', title, ';', body, ';', author]

In [458]:
def handle_single_broken(rowStr): #broken instance on one line. Ends in ';;;;;'
    rowlist = rowStr.split(',')
    length = len(rowlist)
    
    pr = rowlist[0]
    author = rowlist[2]
    
    files = ""
    for j in range(6, length-1):
        file = clean_file(rowlist[j])
        if(len(file) != 0):
            files += file
            
            if(j != length-2):
                files += ';'
                
    title = clean_title(rowlist[length-1])
    body = 'nan'
    
    if(len(files) == 0):
        return []
    else:
        return [pr, ';', files, ';', title, ';', body, ';', author]

In [459]:
pr = ""
hold_files = ""
partial_file = ""
title = ""
body = ""
author = ""


def handle_multiple_broken_start(row): #broken instance on multiple lines; Doesn't end in ';;;;;', last line does
    global pr
    global hold_files
    global partial_file
    global title
    global body
    global author
    
    pr = ""
    hold_files = ""
    partial_file = ""
    title = ""
    body = ""
    author = ""
    
    rowlist = row.split(',')
    length = len(rowlist)
    
    pr = rowlist[0]
    author = rowlist[2]
    
    for j in range(6, length-1):
        file = clean_file(rowlist[j])
        if(len(file) != 0):
            hold_files += file
            hold_files += ';'
    
    #add in broken ending file
    partial_file = rowlist[length-1].replace(';','')
    
def handle_extra_files(row): #extra files following
    global partial_file
    global hold_files
    
    length = pd.DataFrame(row).count().iloc[0]
    
    #handle second half of broken ending file
    partial_file += row[0]
    partial_file = clean_file(partial_file)
    if(len(partial_file) != 0):
        hold_files += partial_file
        hold_files += ';'
    
    for j in range(1, length-1):
        file = clean_file(row[j])
        if(len(file) != 0):
            hold_files += file
            hold_files += ';'
            
    #handle broken ending file at the end of this row
    partial_file = row[length-1].replace(';','')
    
def handle_multiple_broken_end(row): #broken instance on multiple lines. Ends in ';;;;;'
    rowlist = row.split(',')
    length = len(rowlist)
    
    global partial_file
    global hold_files
    
    partial_file += rowlist[0]
    partial_file = clean_file(partial_file)
    if(len(partial_file) != 0):
        hold_files += partial_file
        if(length != 2):
            hold_files += ';'
    
    for j in range(1,length-1):
        file = clean_file(rowlist[j])
        if(len(file) != 0):
            hold_files += file
            if j != length-2:
                hold_files += ';'
    
    title = clean_title(rowlist[length-1])
    body = 'nan'
    
    global pr
    global author
    
    if(len(hold_files) == 0):
        return []
    else:
        return [pr, ';', hold_files, ';', title, ';', body, ';' , author]

In [460]:
def clean_file(file):
    if(type(file) == float): #file == nan => 0 files
        return ""
    if(file.find('.java') == -1):
        return ""
    if(not "/src" in file):
        return ""
    
    file = file.replace("[", "")
    file = file.replace("]", "")
    file = file.replace("\"", "")
    file = file.replace("\'", "")
    file = file.replace(" ", "")
    
    file = file.split('/src',1)[1]
    file = 'src' + file
    return file

def clean_title(title):
    title = title.replace("\n", "")
    title = title.replace("\"", "")
    title = title.replace("\'", "")
    title = title.replace("`", "")
    title = title.replace(";", "")
    title = title.replace(",", "")
    return title

In [461]:
def create_filesPR3BodyTitle2(commitDF):
    filesPR3BodyTitle2List = []
    last_finished = True
    i = 1
    
    for row in commitDF.itertuples(index = False):
        print(i)
        length = pd.DataFrame(row).count().iloc[0]
        
        if(length == 1):
            if(row[0] != ";;;;;"):
                if(row[0].endswith(";;;;;") or row[0].endswith(";;;;")):
                    if(last_finished):
                        list = handle_single_broken(row[0])
                        last_finished = True
                        
                        if not len(list) == 0:
                            print("Added: ", list)
                            filesPR3BodyTitle2List.append(list)
                        
                    else:
                        print("end")
                        list = handle_multiple_broken_end(row[0])
                        last_finished = True
                        
                        if not len(list) == 0:
                            print("Added: ", list)
                            filesPR3BodyTitle2List.append(list)
                        
                else: #row does not end in ;;;;;
                    if(last_finished):
                        print("start")
                        handle_multiple_broken_start(row[0])
                        last_finished = False
                    
                    
                
        else: #length != 1
            if(row[0].find('.') == -1 and last_finished): #the start of a valid row
                list = handle_normal_row(row)
                last_finished = True
                
                if not len(list) == 0:
                    print("Added: ", list)
                    filesPR3BodyTitle2List.append(list)
                            
            if(not last_finished): #need to count extra files
                print("extra files")
                handle_extra_files(row)
                
        i += 1
    return pd.DataFrame(filesPR3BodyTitle2List)

In [462]:
PBT_df = create_filesPR3BodyTitle2(df)

1
2
Added:  ['I001768f8d53c879f8c826e98d24b0130eef344f1', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/AbstractOptimizedConditionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/OptimizedPolicyValueValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/OptimizedPopValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/price/TestOptimizedPolicyValueValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/price/TestOptimizedPopValidationRule.java', ';', 'Validate condition and action spec references', ';', 'nan', ';', '2591']
3
4
5
Added:  ['I006526646bde76663d20e9944cb85c0c0307b4fc', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/base/RestExceptionHandler.java', ';', 'Remove dependency to write rmca in restserviceimpl.base  To make sure its deployable in both read & write rmca.  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '810']
6
7
Added:  ['I006d7ae89ce769c61bd737c38178b44e924a5549', ';', 'src/main/java/com/ericsson/bss/rmca/eventservice/BusinessConfigurationChangeEventSchemaVersion.java;', ';', 'Change bcce schema version to 1.7.0  This updates the bcce schema version for the generated events from 1.6.0 to 1.7.0.  Tracking-Id: TR:IA97197', ';', 'nan', ';', '2427']
8
Added:  ['I00756af13d2cb517bed558f5d8758d2a4e19e5f4', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/price/PriceCreateHelper.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/price/PriceCreateHelperImpl.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/price/PriceCreatorImpl.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/price/TestPriceCreateHelperImpl.java', ';', 'Update POP Creator for internal realation  Updates the Catalog integration Price creator to allow for internal (within the same PO) POP to POP relations', ';', 'nan', ';', '4679']
9
Added:  ['I007586521e73a61abce884421a5e85b2f7d42c9b', ';', 'src/main/java/com/ericsson/bss/rmca/cn/fabric8wrapper/impl/ConfigMapClientImpl.java;src/test/java/com/ericsson/bss/rmca/cn/rest/impl/appconfig/MockClientUtils.java;src/main/java/com/ericsson/bss/rmca/cn/services/appconfig/AppConfigListener.java;src/main/java/com/ericsson/bss/rmca/cn/services/currentstate/CurrentStateConfigHandler.java;src/main/java/com/ericsson/bss/rmca/cn/services/fc/FunctionControlStatusServiceWrapper.java;src/main/java/com/ericsson/bss/rmca/cn/services/globalsystemconfig/GlobalSystemConfigServiceImpl.java;src/test/java/com/ericsson/bss/rmca/cn/services/appconfig/TestAppConfigListener.java;src/test/java/com/ericsson/bss/rmca/cn/services/currentstate/model/TestPartition.java;src/test/java/com/ericsson/bss/rmca/cn/services/currentstate/model/TestState.java;src/test/java/com/ericsson/bss/rmca/cn/services/currentstate/model/TestStateConfig.java;src/test/java/com/ericsson/bss/rmca/cn/services/currentstate/TestCurrentStateConfigHandler.java', ';', 'DUMMY  Tracking-Id:', ';', 'nan', ';', '1530']
10
Added:  ['I00883a4fca7dd79df49b17bef703c8ab55e45194', ';', 'src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/validation/service/TestSupplementaryEntityAccessHelper.java', ';', 'Integrate CDAC version 25.70.0  Integrate new CDAC version 25.70.0', ';', 'nan', ';', '68']
11
12
13
Added:  ['I00de1dd49ce100139be7ff90afa45af48acfd9e4', ';', 'src/main/java/com/ericsson/bss/rmca/copilot/internal/engine/EngineImpl.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/action/ActionRequirementConsumer.java', ';', 'Some minor adjustments  Update error message for missing action Made sure trigger event does not trigger same event more than once', ';', 'nan', ';', '68']
14
15
Added:  ['I00f7289733a4536b4e8dd36d22833033555f573a', ';', 'src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFcStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaHttpStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaMultiLanguageFCListenerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/TestCobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/EntityServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/GlobalListServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/ServiceRegistryHandlerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/TestServiceRegistryHandlerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFcStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaHttpStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaMultiLanguageFCListenerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/TestCobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/EntityServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/GlobalListServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/ServiceRegistryHandlerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFcStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaHttpStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaMultiLanguageFCListenerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/TestCobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/EntityServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/GlobalListServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/ServiceRegistryHandlerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/TestServiceRegistryHandlerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFcStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaHttpStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaMultiLanguageFCListenerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/TestCobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/EntityServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/GlobalListServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/ServiceRegistryHandlerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/TestServiceRegistryHandlerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFcStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaHttpStatusListenerImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/CobaMultiLanguageFCListenerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/functioncontrolservice/impl/TestCobaFunctionControlServiceImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/EntityServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/GlobalListServiceRegistryImpl.java;src/main/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/ServiceRegistryHandlerImpl.java;src/test/java/com/ericsson/bss/rm/coba/core/serviceregistry/impl/TestServiceRegistryHandlerImpl.java', ';', 'Fix FC status subsription  Function control status change subscription in CN env needs to be done using the lowercase namespace (to follow the same value/ pattern used in CobaFunctionDefinitionProvider).  Tracking-Id: EIP', ';', 'nan', ';', '3486']
16
17
18
19
20
21
Added:  ['I01577a836960985ddd9cc1198e25356c192b456e', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/AbstractOptimizedConditionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/OptimizedPolicyValueValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/OptimizedPopValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/price/TestOptimizedPolicyValueValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/price/TestOptimizedPopValidationRule.java', ';', 'Add validation to action/condition cardinality  Adds validation to make we have added actions and conditions to POP/PV', ';', 'nan', ';', '68']
22
23
24
25
Added:  ['I017177c3510470efc1b443e4cbcddacb708954f1', ';', 'src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/utils/OrganizationManager.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/utils/OrganizationManager.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/utils/OrganizationManager.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/utils/OrganizationManager.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/utils/OrganizationManager.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/utils/OrganizationManager.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/utils/OrganizationManager.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;src/main/java/com/ericsson/bss/rm/decomposition/cpm/installbase/WeekdayPeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpm/installbase/TestWeekdayPeriodConverter.java;src/main/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/WeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/cpmconverter/conversion/restconverter/internal/TestWeekdayTimePeriodConverter.java;src/test/java/com/ericsson/bss/rm/decomposition/integrationtest/testcases/TestContactMedium_ITCase.java;', ';', 'Fix for WeekdayPeriod Timezone  - Append Z instead of UTC for UTC timezone  Tracking-Id: TR:IA86451', ';', 'nan', ';', '6591']
26
27
28
Added:  ['I0193b170b8c4964b0e3c2780d0687cc2d4d774ea', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/CompositeValidationRule.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/DescribedRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/AbstractOptimizedConditionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/action/ActionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/ConditionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/OptimizedPolicyValueValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/OptimizedPopValidationRule.java', ';', 'Add interfaces to help with getting sub rule descriptions', ';', 'nan', ';', '2591']
29
30
31

Added:  ['I0569d003584292b545f1cd079fa02e519bbb163d', ';', 'src/main/java/com/ericsson/bss/rmca/copilot/erd/acknowledgement/EntityRequirementAcknowledgement.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/copilot/internal/RestCopilotImpl.java', ';', 'Fix for creation of entity requirement  Update to rest api for ERDs to only include main entity acknowledgement', ';', 'nan', ';', '68']
107
108
Added:  ['I057c7bd75758243f332a0811c4251c9437e1bedb', ';', 'src/main/java/com/ericsson/bss/rmca/configurationprovisioner/tool/GetTestDataPackagesTool.java;src/main/java/com/ericsson/bss/rmca/configurationprovisioner/tool/ProvisionTestDataPackageTool.java;src/main/java/com/ericsson/bss/rmca/copilot/Tool.java;src/main/java/com/ericsson/bss/rmca/copilot/internal/erd/tool/CreateEntityToolProvider.java;src/main/java/com/ericsson/bss/rmca/copilot/internal/erd/tool/GetJsonSchemaTool.java;src/main/java/com/ericsson/bss/rmca/copilot/internal/erd/tool/NavigateToPathTool.java;src/main/java/com/ericsson/bss/rmca/copilot/internal/erd/tool/ViewEntityTool.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/copilot/internal/tool/GetCurrentEntityIdTool.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/copilot/internal/tool/GetEntityDetailsTool.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/copilot/internal/tool/ListEntitiesTool.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/ui/internal/tool/GetMenuTool.java', ';', 'Add UI scope for tools  Adds UI scope for tools', ';', 'nan', ';', '68']
109
110
111
Added:  ['I05a195f4b8255ea59412dca373988fe54c25f421', ';', 'src/main/java/com/ericsson/bss/rmca/utilities/housekeeping/ObsoleteVersionUtils.java', ';', 'Step common datatypes  This reverts commit 69a5f5a4f58585de9dd85dd61edc64c2f83d8721.  Reason for revert: When cn is up to date', ';', 'nan', ';', '4679']
112
113
114
115
116
117
Added:  ['I05d4dabddb3a7924ed8a44072069660fcb049548', ';', 'src/main/java/com/ericsson/bss/rmca/copilot/erd/EntityRequirementConsumerContext.java;src/main/java/com/ericsson/bss/rmca/copilot/internal/erd/EntityRequirementConsumersImpl.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/action/ActionRequirementConsumer.java;', ';', ' then value must be integer value (no decimal points allowed)', ';', 'nan', ';', '68']
118
119
120
Added:  ['I06201d6915969b9bef012a7ea57baecd4af4b110', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/coba/CobaConstants.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/GeneralLedgerCodePage.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/GeneralLedgerCodePageConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/GeneralLedgerCodePageDetails.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/GeneralLedgerCodePageDetailsSettings.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/GeneralLedgerCodePageProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/TestGeneralLedgerCodePage.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/TestGeneralLedgerCodePageConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/TestGeneralLedgerCodePageDetails.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/TestGeneralLedgerCodePageDetailsSettings.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/generalledgercode/TestGeneralLedgerCodePageProvider.java', ';', 'Add general ledger code page  Add the general ledger code page  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '9255']
121
Added:  ['I0625a0ff70003342a5f92fe2d5f1856ba7012cab', ';', 'src/main/java/com/ericsson/bss/rmca/validation/validation/rules/instance/globallist/GloballistOverLappingValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/instance/globallist/TestGloballistOverLappingIpv4ValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/instance/globallist/TestGloballistOverLappingIpv6ValidationRule.java', ';', 'Update overLapping range values validation  Updates the validation to validate column data only against columns with the same column name when checking for NO_OVERLAP_WITHIN_LIST.', ';', 'nan', ';', '8734']
122
Added:  ['I06280dc26f12a23b1c14876e4d8b673f1eefc408', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/DeleteProductOfferingVersionTransaction.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/DeleteVersionTransactionImpl.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/AdvancedWriteServiceImpl.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/WriteServiceImpl.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/WriteServiceSpecificationUpdater.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/transaction/TestDeleteVersionTransactionImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/TestAdvancedWriteServiceImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/TestWriteServiceImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/TestWriteServiceOperationBuilder.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/TestWriteServiceSpecificationUpdater.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/writeservice/WriteService.java;src/main/java/com/ericsson/bss/rmca/utilities/entity/VersionUtil.java;src/test/java/com/ericsson/bss/rmca/utilities/entity/TestVersionUtil.java;', ';', ' with a single CIL operation', ';', 'nan', ';', '4679']
123
Added:  ['I06309c58b5b6ece9286ea1218e8e8d0d28728f31', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/operation/BatchAdvancedWriteOperationImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/operation/TestBatchAdvancedWriteOperationImpl.java', ';', 'Fix for Batch Advanced write when delete versions  Fixes the BatchAdvancedWriteOperation when deleting versions would still contain the deleted version in the main version list', ';', 'nan', ';', '4679']
124
Added:  ['I063bf4861d1c197740b01d58dccdcb1752f4a19f', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/configuration/action/ImprovedActionsConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/configuration/dimension/ImprovedDimensionsConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/definition/dimension/DimensionsDefinitionFactory.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/configuration/action/TestImprovedActionsConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/configuration/dimension/TestImprovedDimensionsConverter.java', ';', 'Update PO improved action/dimension converters  Updates to action/dimensions converter to generate ids for missing levels in same was as in rule builder', ';', 'nan', ';', '68']
125
126
127
128
129
Added:  ['I066b577e328ceec04247720587567734d7d471a5', ';', 'src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/ReferencesPage.java;src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/SpecBrowserImpl.java;src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/SpecPage.java;', ';', 'Add references page to specbrowser  Adds page to allow user to view all references and their paths directly in specbrowser', ';', 'nan', ';', '68']
130
131
132
start
133
134
extra files
135
extra files
136
extra files
137
end
138
139
Added:  ['I069f5cd765db36754c8b37c8712beb606871363a', ';', 'src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/ExportSpecListPage.java;src/main/java/com/ericsson/bss/rmca/integrationtest/specbrowser/internal/SpecBrowserImpl.java', ';', 'Fix for export of POT in specbrowser  Fix issue with POT not being exported from export-zip', ';', 'nan', ';', '68']
140
141
142
Added:  ['I06bc2397e1f447bf729f4e54612e3c2dcbd3140d', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/definition/dimension/DimensionsDefinitionFactory.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/definition/dimension/TestDimensionsDefinitionFactory.java', ';', 'Update PO dimensions definition factory  Updates PO dimensions definition factory to create dimension definitions from dimension specifications', ';', 'nan', ';', '68']
143
144
Added:  ['I06dae8baec5bfec6143da244d6117f33320375fd', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/EntityConverterUtilities.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/ResourceSpecificationConverter.java;src/main/java/com/ericsson/bss/rmca/rollback/transactionlog/impl/TransactionLogEntryConverter.java', ';', 'Replace usage of persistence object ctors  Replaces the calls to the parameterized constructors of the persistence objects with the objects builder instead to avoid breaking compatibility if new fields are added to the object.', ';', 'nan', ';', '2591']
145
146
Added:  ['I06f90264ce5bf4e6b19ecc6b2f75203e3a5f0416', ';', 'src/main/java/com/ericsson/bss/rmca/persistenceimpl/ClusterFacade.java;src/main/java/com/ericsson/bss/rmca/persistenceimpl/EntityTypeInfoPersistenceServiceImpl.java;src/main/java/com/ericsson/bss/rmca/persistenceimpl/UnversionedPersistenceImplBase.java;src/main/java/com/ericsson/bss/rmca/persistenceimpl/VersionPersistenceServiceImpl.java', ';', 'Load POs from CIL in segments  Example patch to demonstrate new PO loading from CIL. Number of Segments value is proposed by CIL.', ';', 'nan', ';', '890']
147
Added:  ['I0704e48ba9d8829734810cefdb7084f4ca55a3ee', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/operation/BatchAdvancedWriteOperationImpl.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/transaction/BatchWriteTransactionImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/operation/TestBatchAdvancedWriteOperationImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/transaction/TestBatchWriteTransactionImpl.java', ';', 'Expose entity for metadata from Advanced Batch op  Exposes the current entity for metadata from the Advanced Batch operation. Can be used to access the current state of the enity whilst building the operation', ';', 'nan', ';', '4679']
148
149
150
151
152
153
Added:  ['I0751e34e0ac14a3a1d317c0c5b4e4e7f77c4cb8d', ';', 'src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/TypedValue.java;src/main/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/values/ValueRange.java;src/test/java/com/ericsson/bss/rmca/validation/validation/utils/typedvalue/TestTypedValue.java', ';', 'Add support for time period values to typed value  Adds support for time of day and date time period to typed value', ';', 'nan', ';', '68']
154
Added:  ['I075db8198166ca7dbb1baf948b00d78755800e74', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/datalist/DataListPageConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/datalist/TestDataListPageConverter.java', ';', 'Fix valueType for derived data type  If the derived data type has a weird name which would resolve to a valid valueType of a different type it would.  Update so if its a derived data type it will always be string.  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '9255']
155
156
157
Added:  ['I078782457edec73e881f5374ccdfcc7bf75652ce', ';', 'src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java;src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java;', ';', 'Bump Bssf Specification Management Converter version  Bssf Specification Management Converter 1.7.0 COBA CDAC 8.134.0 COBA DataWriter 6.136.0', ';', 'nan', ';', '1530']
158
159
Added:  ['I07cc2b30928bcc3eebafa9d5da78bce45b2204c9', ';', 'src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/catalogintegration/AbstractProductOfferingApiTest.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/ProductOfferingApiImpl.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/TestProductOfferingApiImpl.java', ';', 'Add FC check to catalog integration  Adds check for function control before create and throw service unavailable exception if not active', ';', 'nan', ';', '68']
160
161
162
Added:  ['I07ec618b7767e284dc293b734faac25b98918d03', ';', 'src/main/java/com/ericsson/bss/coba/fabric8wrapper/impl/ConfigMapClientImpl.java;', ';', 'Bump versions  Add BEAM Chassis features dependency - BEAM Chassis 0.12.0-4 - Use BEAM Chassis features:   beam-platform-performance-management   beam-platform-kubernetes-client  BAM Chassis versions - Adapt to new Alarm Handler proxy.  BAM OAM 2.18.0-5 BAM AlarmHandler API 1.7.0-2 BAM FM Rest 1.7.0-2 BAM OAM DataCollection 1.7.0-1 BAM OAM FC 1.24.0-1 BAM OAM PM 1.18.0-2 BAM OAM FM Handler 1.30.0-2 BAM Karaf Prometheus Servlet 1.9.0-2 BAM Jetty Fragment 1.6.0-1 BAM OAM 3pp Features 2.18.0-5 BAM OAM Chassis Features 2.18.0-5  Gson On Fire! 1.9.0 Okio 3.9.0 ASM 9.7 Fabric8 6.13.3 Fabric8 Karaf 6.13.0-2 CIL Client k8s Configurator 5.4.9 NetworkNt Json Schema Validator 1.2.0 ITU 1.10.2 UnboundId Ldap SDK 6.0.11 Snappy-Java 1.1.10.6 Javassist 3.30.2-GA Netty 4.1.112.Final MSG Client 1.21.0-11 Kafka v3 3.7.0_1 IOD Trace API 2.0.1 Micrometer 1.12.2 Prometheus SimpleClient 0.16.0 HdrHistogram 2.2.2 FasterXml Jackson 2.17.2 CXF 3.6.4 Gson 2.11.0 HttpComponents HttpClient OSGi 4.5.14 Karaf 4.4.6 SnakeYaml 2.3', ';', 'nan', ';', '1031473']
163
164
Added:  ['I07fdc6d4b2ca68525c7b287bcab58b8215cf03ac', ';', 'src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/CachedViewImpl.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewFactoryImpl.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/CachedViewImpl.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewFactoryImpl.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/CachedViewImpl.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewFactoryImpl.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/CachedViewImpl.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/view/ViewFactoryImpl.java', ';', 'Add logging for the Cache initialization  The following will be logged:   * the initialization of the caches (INFO)  * whenever a cache initialization is complete (INFO)    - this also keeps tracks of current completed cache initializations  * which specifications (id) and its type that are cached (DEBUG)', ';', 'nan', ';', '1550']
165
166
167
Added:  ['I0815b2ff3cc40d9d1de2b08368dce725a5cdfd4c', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/RuleConverterContext.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/AbstractCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/base/TestRuleConverterContext.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/aggregatedcharges/TestAggregatedChargesCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/discountononetimechargerule/TestDiscountOnOneTimeChargeCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/lifecyclerule/TestLifecycleCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/onetimechargerule/TestOneTimeChargeCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/partnersettlement/TestPartnerSettlementCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/promotionrule/TestPromotionCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/recurrencerule/TestRecurrenceCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/servicetriggeredrule/TestServiceTriggeredCommonDimensionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/TestServiceUsageCommonDimensionListProvider.java', ';', 'Add filtering of common dimension based on format  Adds filtering to make sure only common dimension with matching format of rule are listed as available', ';', 'nan', ';', '68']
168
Added:  ['I081d916f93476c161eb594daa63274beae957f4b', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/coba/CobaConstants.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/LifecycleTypePage.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/LifecycleTypePageConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/LifecycleTypePageDetails.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/LifecycleTypePageDetailsSettings.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/LifecycleTypePageProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/TestLifecycleTypePage.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/TestLifecycleTypePageConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/TestLifecycleTypePageDetails.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/TestLifecycleTypePageDetailsSettings.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecycletype/TestLifecycleTypePageProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/TestNumberClassPageConverter.java', ';', 'Add page for lifecycle type  Add the page for lifecycle type  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '9255']
169
170
171

1505
1506
1507
1508
1509
Added:  ['I3e2c47f89c815f2d9198f332960363bf8b33dac3', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/rulebuilder/ActionMetaInfo.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationResult.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/internal/helpers/RestResponseWrapper.java', ';', 'Stop implementing serializable  To resolve sonar issues.  Tracking-Id: EIP', ';', 'nan', ';', '810']
1510
Added:  ['I3e57f0b8bc2f391849de55ca2deb9fb106ca3e8f', ';', 'src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/entity/PolicyValueSpecificationDependencyAnalyzer.java;src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/entity/ProductOfferingDependencyAnalyzer.java;src/main/java/com/ericsson/bss/rmca/utilities/entity/dependency/entity/ProductOfferingPriceSpecificationDependencyAnalyzer.java;', ';', ' POPS and PO so that references from improved price model are reported without path (excluded from validation) as this was the result of legacy where references are all found in characteristics', ';', 'nan', ';', '68']
1511
1512
1513
Added:  ['I3e802935aebdab1f6c7de670a0387556f5729607', ';', 'src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ConfigurationProvisionerImpl.java;src/main/java/com/ericsson/bss/rmca/configurationprovisioner/entitycreator/MultiVersionEntityCreator.java;src/test/java/com/ericsson/bss/rmca/configurationprovisioner/entitycreator/TestMultiVersionEntityCreator.java;src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java;src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ConfigurationProvisionerImpl.java;src/main/java/com/ericsson/bss/rmca/configurationprovisioner/entitycreator/MultiVersionEntityCreator.java;src/test/java/com/ericsson/bss/rmca/configurationprovisioner/entitycreator/TestMultiVersionEntityCreator.java;src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java;src/main/java/com/ericsson/bss/rmca/configurationprovisioner/ConfigurationProvisionerImpl.java;src/main/java/com/ericsson/bss/rmca/configurationprovisioner/entitycreator/MultiVersionEntityCreator.java;src/test/java/com/ericsson/bss/rmca/configurationprovisioner/entitycreator/TestMultiVersionEntityCreator.java;src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/AbstractEntityTest.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java', ';', 'Fix for configuration provisioner  Removed dependency between configuration provisioner and housekeeping service', ';', 'nan', ';', '68']
1514
1515
1516
1517
1518
Added:  ['I3ec977435003e103eacfa7c00b263757b247525e', ';', 'src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/RangeLimitValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/TieredBucketMeasureRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/TestRangeLimitValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/TestTieredBucketMeasureRule.java', ';', 'Get measure of referenced char for range limits  Include the measure of referenced characteristics in range validation rules.', ';', 'nan', ';', '2591']
1519
Added:  ['I3ecf5f816f9de95c2fa5785bc50f9c8628c97cea', ';', 'src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/ProductOfferingConverter.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/ProductOfferingPriceSpecificationConverter.java;src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestProductOfferingPriceSpecificationConverter.java;src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/Dimension.java;src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/DimensionSpecification.java;src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/EntityFactoryHelper.java;src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestDimension.java;src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestDimensionSpecification.java;src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingPrice.java;src/test/java/com/ericsson/bss/rmca/entityserviceviews/cdac/TestProductOfferingPriceSpecificationVersion.java;src/test/java/com/ericsson/bss/rmca/persistenceimpl/TestEntitySchemaFactory.java;', ';', 'Add description to dimension and dimension spec  Adds description field to dimension and dimension specification', ';', 'nan', ';', '68']
1520
1521
1522
1523
1524
1525
1526
Added:  ['I3f31e9b05085033718b6d10da031e59ac9e08274', ';', 'src/main/java/com/ericsson/bss/rmca/configurations/sharp/rmca/Ft42193Refund.java;src/main/java/com/ericsson/bss/rmca/configurations/sharp/SharpTestDataPackages.java;', ';', 'FT42-193 Refund', ';', 'nan', ';', '2591']
1527
Added:  ['I3f33097fd3f0e4eff7aece03b89a59a5098be2bd', ';', 'src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/catalogintegration/AbstractProductOfferingApiTest.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/catalogintegration/TestProductOfferingApiCreate.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/PolicyRefCreatorImpl.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/PoPolicyCreateGroup.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/PoPolicyCreateHelper.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/PoPolicyCreateHelperImpl.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/PoPolicyCreateInfo.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/PoPolicyCreateRequestWrapper.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/TestPolicyRefCreatorImpl.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/TestPoPolicyCreateGroup.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/TestPoPolicyCreateHelperImpl.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/TestPoPolicyCreateInfo.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/policyref/TestPoPolicyCreateRequestWrapper.java', ';', 'Update PO policy ref creator  Updates Catalog integration PO policy ref creator to take in the request as an absolute list of POPolicyRefs', ';', 'nan', ';', '4679']
1528
Added:  ['I3f33e64040c966d65e9506a6c6f48c6e901d4e3b', ';', 'src/main/java/com/ericsson/bss/rmca/cdac/impl/internal/RmcaGlobalListSpecificationQuery.java;src/test/java/com/ericsson/bss/rmca/cdac/impl/internal/TestRmcaGlobalListSpecificationQuery.java;', ';', ' we hard coded the new columns as there wont be any changes to them in the future. and to avoid unnecessary read requests.', ';', 'nan', ';', '8734']
1529
1530
1531
start
1532
1533
end

Added:  ['I70a35734fec6d915567a53782b306d7cb08111e1', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/CreatorHelper.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/CreatorHelperImpl.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/catalogintegration/internal/converters/TestCreatorHelperImpl.java', ';', 'Update creator helper in catalog integration  Updatas creator helper to make single relation/characteristic creation helper methods public so they can be used for single relations on POP and APOP', ';', 'nan', ';', '68']
2757
2758
2759
Added:  ['I70bc84f888649043ed187b983795feb656e7ca27', ';', 'src/main/java/com/ericsson/bss/rmca/utilities/rule/action/ActionAttributeTypeHelper.java;src/main/java/com/ericsson/bss/rmca/utilities/rule/condition/ConditionAttributeTypeHelper.java;src/test/java/com/ericsson/bss/rmca/utilities/rule/action/TestActionAttributeTypeHelper.java;src/test/java/com/ericsson/bss/rmca/utilities/rule/condition/TestConditionAttributeTypeHelper.java;', ';', ' bucket tag etc', ';', 'nan', ';', '68']
2760
2761
2762
Added:  ['I70cf65bf0366c18cd2391fe7c310d5f5fdf21f64', ';', 'src/main/java/com/ericsson/bss/rmca/copilot/erd/billingaccountbucket/BillingAccountBucketRequirement.java;src/main/java/com/ericsson/bss/rmca/copilot/erd/productbucket/ProductBucketRequirement.java;src/main/java/com/ericsson/bss/rmca/copilot/internal/schema/CurrenciesSchemaCustomizer.java;src/main/java/com/ericsson/bss/rmca/copilot/internal/schema/UnitsSchemaCustomizer.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/billingaccountbucket/BillingAccountBucketEntityRequirementConsumer.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productbucket/ProductBucketEntityRequirementConsumer.java', ';', 'Allow units as unit type  Update copilot API to allow units as unit types', ';', 'nan', ';', '68']
2763
Added:  ['I70d54b2556a761a188e572727c8561860ddf1eac', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/ServiceUsageConditionListProvider.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateProvider.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplate.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TieredRateTemplateConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/serviceusagerule/TestServiceUsageConditionListProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/rulebuilder/condition/tieredrate/TestTieredRateTemplate.java;', ';', ' its converter and provider This will allow UI to display a single name for this condition as it does for all other conditions', ';', 'nan', ';', '68']
2764
Added:  ['I70d80d42d5fff6b12a480841cce28ab9392c2a5b', ';', 'src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/common/TestRelationToProductOfferingTemplate.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/RelationToProductOfferingTemplate.java', ';', 'Update validation rule to ignore self  Update the validation rule for not allowing to point to a template offering.  Added filter to remove relations to itself.  Tracking-Id: BSUC:FT8-145:1', ';', 'nan', ';', '9255']
2765
Added:  ['I70fe367bc4f1e246f9293bf5db48fc2a1197d377', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/ProductSpecificationAdapter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/converter/ProductSpecificationConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/ProductSpecificationAdapter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/converter/ProductSpecificationConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/ProductSpecificationAdapter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/converter/ProductSpecificationConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/adapter/ProductSpecificationAdapter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/traffic/converter/ProductSpecificationConverter.java', ';', 'Add normalizedeventspecification to PS rest  This adds normalized event specifications to product specification rest adapter and converter.  Tracking-Id: TR:IA80927', ';', 'nan', ';', '2427']
2766
2767
Added:  ['I711953afa47d0ae3d637cf40936d48e8853cd239', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/coba/CobaConstants.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/validation/BusinessConfigurationRestValidator.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/validation/TestBusinessConfigurationRestValidator.java', ';', 'Allow whitespace for simple entity  Allow whitespace for simple entity in the public key.  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '9255']
2768
2769
Added:  ['I7172fbd38f9542f477a6d818240a75249612805c', ';', 'src/main/java/com/ericsson/bss/rmca/jive/cn/testcases/ProductOfferingTest.java;src/main/java/com/ericsson/bss/rmca/jive/suite/RmcaCAFSuite.java;src/main/java/com/ericsson/bss/rmca/jive/testcases/NesServiceRegistryTest.java;src/main/java/com/ericsson/bss/rmca/jive/testcases/ProductOfferingTest.java', ';', 'Revert Prepare jive test for removing internal interfaces  This reverts commit 3c996db430ac1acc719ac30047a3a30c011993ee.  Reason for revert: Jive tests fail on virtual track', ';', 'nan', ';', '810']
2770
Added:  ['I7180b6d336ee178f2b5717b034eca4e3e6d12fa3', ';', 'src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/definition/action/ActionAttributeCharacteristicFacadeFactory.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/definition/action/ActionCharacteristicFacadeFactory.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/businessstrategies/definition/action/value/TestValueDefinitionFactoryWithOptimizedFormat.java', ';', 'Add unit test for optimized model  Duplicates existing unit test and update them for optimized price model', ';', 'nan', ';', '68']
2771
Added:  ['I7196005b8dc5ade0028335e29dfb081bffeabfc2', ';', 'src/main/java/com/ericsson/bss/rmca/validation/validation/rules/instance/globallistspecification/GlobalListSpecificationColumnMandatoryFieldsValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/instance/globallistspecification/GlobalListSpecificationMandatoryFieldsValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/service/InstanceValidationFactoryImpl.java;src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/instance/GlobalListSpecificationValidationRuleProvider.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/instance/globallistspecification/TestGlobalListSpecificationColumnMandatoryFieldsValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/instance/globallistspecification/TestGlobalListSpecificationMandatoryFieldsValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/service/provider/instance/TestGlobalListSpecificationValidationRuleProvider.java;src/test/java/com/ericsson/bss/rmca/validation/validation/service/TestInstanceValidationFactoryImpl.java', ';', 'Add GLS mandatory fields validation rule  Adds mandatory fields validation rule for globallist specification and globallistSpecification columns', ';', 'nan', ';', '8734']
2772
2773
2774
2775
2776
Added:  ['I71ba44e431e3b7a889db1e60ceba4e69e9f98198', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/list/SortKey.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfigurationlistpageservice/BusinessConfigurationRestListPageImpl.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfigurationlistpageservice/TestBusinessConfigurationRestListPageImpl.java', ';', 'Add groupBy support  Add groupBy support for business configuration  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '9255']
2777
Added:  ['I71d87adcaa8b0b165f4a4040d70307c2d8daeba0', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/deriveddatatype/DerivedDataTypePageConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecyclestate/LifecycleStatePageConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/deriveddatatype/TestDerivedDataTypePageConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/lifecyclestate/TestLifecycleStatePageConverter.java', ';', 'Fix derived data type and lifecycle state  Derived data type was missing existing public keys for the skeleton page  Lifeycycle state had  the wrong type set  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '9255']
2778
Added:  ['I71ddd465533493705545012a5cab3eefa28cde0e', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java;src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/ImportValidationErrorMessage.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestImportValidationErrorMessage.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfAnyDefinitionVersionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfAnyUnlockedVersionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendOnlyAllowedForSpecificEntityTypesValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfAnyDefinitionVersionValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfAnyUnlockedVersionValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfUsedByNonSuspendedValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendOnlyAllowedForSpecificEntityTypesValidationRule.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java;src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/ImportValidationErrorMessage.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestImportValidationErrorMessage.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/NoReferencedEntityCanBeSuspendedValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfAnyDefinitionVersionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfAnyUnlockedVersionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfUsedByNonSuspendedValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendOnlyAllowedForSpecificEntityTypesValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestNoReferencedEntityCanBeSuspendedValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfAnyDefinitionVersionValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfAnyUnlockedVersionValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfUsedByNonSuspendedValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendOnlyAllowedForSpecificEntityTypesValidationRule.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java;src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/ImportValidationErrorMessage.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestImportValidationErrorMessage.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/NoReferencedEntityCanBeSuspendedValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfAnyDefinitionVersionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfAnyUnlockedVersionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfUsedByNonSuspendedValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendOnlyAllowedForSpecificEntityTypesValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestNoReferencedEntityCanBeSuspendedValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfAnyDefinitionVersionValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfAnyUnlockedVersionValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfUsedByNonSuspendedValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendOnlyAllowedForSpecificEntityTypesValidationRule.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java;src/test/java/com/ericsson/bss/rmca/entitymodificationviews/validation/TestValidationErrorFactory.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/ImportValidationErrorMessage.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/extendedtraffic/expimp/TestImportValidationErrorMessage.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfAnyDefinitionVersionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendNotAllowedIfAnyUnlockedVersionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendOnlyAllowedForSpecificEntityTypesValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfAnyDefinitionVersionValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfAnyUnlockedVersionValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendNotAllowedIfUsedByNonSuspendedValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendOnlyAllowedForSpecificEntityTypesValidationRule.java', ';', 'Add import validation messages  This adds housekeeping import validation messages.  Tracking-Id: TR:IA90685', ';', 'nan', ';', '2427']
2779
2780
2781
2782
Added:  ['I723c3ae71cef8be3506effb51c470b221da6be61', ';', 'src/main/java/com/ericsson/bss/rmca/cdac/api/IncludeSuspendedSpecificationsParameter.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryParameterFactoryImpl.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/internal/QueryParameterFlags.java;src/main/java/com/ericsson/bss/rmca/entityserviceimpl/NonSuspendedFilter.java;src/test/java/com/ericsson/bss/rmca/entityserviceimpl/internal/TestPublicQueryFactoryImpl.java;src/test/java/com/ericsson/bss/rmca/entityserviceimpl/TestNonSuspendedFilter.java;src/main/java/com/ericsson/bss/rmca/entityserviceviews/cdac/QueryParameterFactory.java;src/main/java/com/ericsson/bss/rmca/cdac/impl/internal/RmcaCdacQuery.java;src/test/java/com/ericsson/bss/rmca/cdac/impl/internal/TestRmcaCdacQuery.java', ';', 'Add logic to expose suspended specs  Existing filter is updated to expose suspended specs. New query paramter is added used in the filter.  Tracking-Id: BSUC:FT8-147', ';', 'nan', ';', '322']
2783
2784
2785
Added:  ['I7264fef4832f42cef9fc165970f212ac0ecc2ce6', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/entities/DataItemType.java', ';', 'Add missing data item types  Add types missing  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '9255']
2786
2787
Added:  ['I7291b1800dd2c1df05396875196c3a78d0687a33', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/AdvancedWriteServiceImpl.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/WriteServiceImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/TestAdvancedWriteServiceImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/writeservice/TestWriteServiceImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/MockQueryFactory.java;src/main/java/com/ericsson/bss/rmca/examples/RmcaWriteServiceFactory.java;src/main/java/com/ericsson/bss/rmca/housekeeping/impl/HousekeepingServiceImpl.java;src/test/java/com/ericsson/bss/rmca/housekeeping/impl/TestHousekeepingServiceImpl.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/ServiceInitializer.java;src/main/java/com/ericsson/bss/rmca/utilities/entity/ListUnfilteredQueryFactory.java;src/main/java/com/ericsson/bss/rmca/utilities/housekeeping/ObsoleteVersionUtils.java;src/test/java/com/ericsson/bss/rmca/utilities/entity/TestListUnfilteredQueryFactory.java;src/test/java/com/ericsson/bss/rmca/utilities/housekeeping/TestObsoleteVersionUtils.java', ';', 'Update HKS and WriteServices to use UQF  Updates the HousekeepingService and the WriteServices to use the UnfilteredQueryFactory', ';', 'nan', ';', '4679']
2788
2789
Added:  ['I729cd396aee9cae9766a218e77f4d9a0847286b2', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/instance/SystemDefinedEntities.java', ';', 'Add list of system defined entities  To be used by write logic.  Tracking-Id: BSUC:FT42-190:1', ';', 'nan', ';', '810']
2790
Added:  ['I729e48043ad81cc3c469af3d4b4fd150d2c2d4d3', ';', 'src/main/java/com/ericsson/bss/rmca/cdac/generator/Generator.java;src/main/java/com/ericsson/bss/rmca/cdac/generator/Generator.java', ';', 'Fix for null RARSuppressingInformation  add mapping to generator to align datatypes and cdac impl  Tracking-Id: TR:IB18805', ';', 'nan', ';', '5254']
2791
2792
2793

5216
5217
5218
5219
5220
5221
Added:  ['Id8bd0f12c71a6b54feb6e919e822b7cdb763d32b', ';', 'src/main/java/com/ericsson/bss/rmca/cdac/instancegenerator/EntityConverters.java;src/main/java/com/ericsson/bss/rmca/cdac/instancegenerator/EntityServiceVersionedViewsApiGenerator.java;src/main/java/com/ericsson/bss/rmca/cdac/instancegenerator/EntityServiceViewlInstanceConvertersGenerator.java;src/main/java/com/ericsson/bss/rmca/cdac/instancegenerator/instancetypes/InstanceClass.java;src/main/java/com/ericsson/bss/rmca/cdac/instancegenerator/instancetypes/InstanceField.java;src/main/java/com/ericsson/bss/rmca/cdac/instancegenerator/instancetypes/NameMutator.java;src/main/java/com/ericsson/bss/rmca/cdac/instancegenerator/instancetypes/NameType.java', ';', 'Revert Align InstanceGenerator  This reverts commit 882b496dd59cca64288b5f560c9c0ffcf6aed9aa.  Reason for revert: failure in rmca', ';', 'nan', ';', '810']
5222
5223
Added:  ['Id8c888ec75a201cd1f9e82250a5763243675b900', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/OneEntityConfigurationProvisioner.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedAggregatedChargesProvisioner.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBillingCycleAlignedScheduleDefinitionProvisioner.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedBucketTagSetProvisioner.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedEntityProvisioningException.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyCounterStatusProvisioner.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedNetworkPolicyGroupPrioListProvisioner.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedPartyRoleSpecificationProvisioner.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedPolicyEventsProvider.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/PredefinedSharingProviderPrioListProvisioner.java;src/main/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/provisioning/ProvisionConfigurationServiceImpl.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/configuration/TestThatNoUntestedProvisionersAreAdded.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestOneEntityConfigurationProvisioner.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedBillingCycleAlignedScheduleDefinitionProvisioner.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedBucketTagSetProvisioner.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedNetworkPolicyCounterStatusProvisioner.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedNetworkPolicyGroupPrioListProvisioner.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedPolicyEventsProvider.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedRecurrencePrioListProvisioner.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/predefined/TestPredefinedSharingProviderPrioListProvisioner.java;src/test/java/com/ericsson/bss/rmca/entitymodificationimpl/internal/configuration/TestPredefinedConfigsAreStatic.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/rule/TestRuleTypeFactoryVsRuleContextTypeConverter.java;src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/catalogManagement/TestCatalogManagement_ITCase.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/helpers/agreementspecification/TestEnrichedProductOfferingHelper.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productspecification/TestProductSpecificationPageConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productspecification/TestProductSpecificationPageConverterOnAllProductSpecifications.java;', ';', ' GEN:LOW', ';', 'nan', ';', '810']
5224
Added:  ['Id8d50165d39e1a5599cceb8be3b1de598e8ab743', ';', 'src/main/java/com/ericsson/bss/rmca/persistenceimpl/VersionPersistenceServiceImpl.java;src/test/java/com/ericsson/bss/rmca/persistenceimpl/TestVersionPersistenceServiceImpl.java;src/main/java/com/ericsson/bss/rmca/persistenceservice/VersionedPersistenceService.java;', ';', ' adding a new method to the interface that will persist a provided list of Enity Versions to CIL', ';', 'nan', ';', '4679']
5225
5226
Added:  ['Id8de60bbaf83267782dffd9428358259e887db9f', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/coba/CobaConstants.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/NumberClassPage.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/NumberClassPageConverter.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/NumberClassPageDetails.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/NumberClassPageDetailsSettings.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/NumberClassPageProvider.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/TestNumberClassPage.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/TestNumberClassPageConverter.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/TestNumberClassPageDetails.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/TestNumberClassPageDetailsSettings.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfiguration/pages/numberclass/TestNumberClassPageProvider.java', ';', 'Add number class page  Add the page for number class  Tracking-Id: BSUC:FT42-190:3', ';', 'nan', ';', '9252']
5227
5228
5229
Added:  ['Id92a515f6f2c4c5133f2d2ae6c56d6e794e5e7b4', ';', 'src/main/java/com/ericsson/bss/rmca/copilot/erd/businessstrategy/ActionHolderRequirement.java;src/main/java/com/ericsson/bss/rmca/copilot/erd/businessstrategy/ConditionHolderRequirement.java;src/main/java/com/ericsson/bss/rmca/copilot/erd/businessstrategy/PriceConfigurationRequirement.java;src/main/java/com/ericsson/bss/rmca/copilot/erd/productoffering/ActionHolderRequirement.java;src/main/java/com/ericsson/bss/rmca/copilot/erd/productoffering/ConditionHolderRequirement.java;src/main/java/com/ericsson/bss/rmca/copilot/erd/productoffering/StatementRequirement.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/action/ActionRequirementConsumer.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/action/ActionRequirementConsumers.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/action/ActionRequirementProducer.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/action/ActionRequirementProducers.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/condition/AvailableUnitsRequirementProducer.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/condition/ConditionRequirementProducer.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/condition/ConditionRequirementProducers.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/productoffering/ProductOfferingEntityRequirementConsumer.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/rule/RuleEntityRequirementConsumer.java;src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/copilot/erd/rule/RuleEntityRequirementProducer.java', ';', 'Refactor ERD to support multiple action/condition  Refactored ERD to support multiple actions and conditions', ';', 'nan', ';', '68']
5230
5231
5232
5233
5234
5235
5236
5237
Added:  ['Id95a39f5ee6ab61f778564305c3fb29b912629dd', ';', 'src/main/java/com/ericsson/bss/rmca/configurations/sharp/rmca/Ft42193UpToTheLimit.java;src/main/java/com/ericsson/bss/rmca/configurations/sharp/SharpTestDataPackages.java;', ';', 'FT42-193 UpToTheLimit', ';', 'nan', ';', '2591']
5238
Added:  ['Id9847a1b993940a043ac1e15560d2195914ec294', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/service/provider/TestCommonValidationRuleProvider.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/common/SuspendedNotAllowedToChangeCommercialEndDateValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/service/provider/CommonValidationRuleProvider.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/common/TestSuspendedNotAllowedToChangeCommercialEndDateValidationRule.java', ';', 'Add validation for end date on suspended  This adds a validation rule that checks if commercial end date is changed on suspended entity.  Tracking-Id: BSUC:FT42-250', ';', 'nan', ';', '2427']
5239
Added:  ['Id98b1e01f8f69d6a45d055096224c210fad49af2', ';', 'src/main/java/com/ericsson/bss/rmca/jive/configuration/RmcaConfiguration.java', ';', 'Testing provisioning of data', ';', 'nan', ';', '9342']
5240
Added:  ['Id98e384112a2dd0bf5ce91c8b349ff185358b76f', ';', 'src/main/java/com/ericsson/bss/rm/coba/jive/testcases/bamsuite/CobaSFCTest.java;src/main/java/com/ericsson/bss/rm/coba/jive/testcases/bamsuite/ImportExportBusinessConfigurationTest.java', ';', 'Fix importExport', ';', 'nan', ';', '8734']
5241
Added:  ['Id997a34fda058d153321e009b59f2662edda7196', ';', 'src/main/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/characteristic/ActionCharacteristicSpecificationValue.java;src/main/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/ActionCharacteristicRecipe.java;src/main/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/ActionRecipe.java;src/main/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/DefaultCharValueRangeSupplier.java;src/main/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/ProductPriceRecipe.java;src/main/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/ProductPriceRecipeSupplier.java;src/test/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/characteristic/TestActionCharacteristicSpecificationValue.java;src/test/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/TestActionCharacteristicRecipe.java;src/test/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/TestActionRecipe.java;src/test/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/TestDefaultCharValueRangeSupplier.java;src/test/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/TestProductPriceRecipe.java;src/test/java/com/ericsson/bss/rm/decomposition/dataaccess/impl/recipe/TestProductPriceRecipeSupplier.java', ';', 'Add ActionRecipe and ActionCharacteristicRecipe  - Add ActionRecipe and ActionCharacteristicRecipe   and its supplier  Tracking-Id: BSUC:FT42-193', ';', 'nan', ';', '6591']
5242
5243
Added:  ['Id9bbff7722fb11b24699b656b118564d210329eb', ';', 'src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/AbstractMetadataFactory.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/action/AbstractActionMetadataFactory.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/AttributeMetadata.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/AbstractConditionMetadataFactory.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/AbstractTieredConditionMetadataFactory.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/CharacteristicConditionMetadataFactory.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/DateTimeIntervalConditionMetadataFactory.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/GlobalTableQueryConditionMetadataFactory.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/ExternalReferenceMetadata.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/InternalReferenceMetadata.java;src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/ReferenceMetadata.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/AbstractMetadataFactoryTest.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/action/TestConsumptionAccumulatorMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/action/TestSessionSetupFeeMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/action/TestSetFixedPriceMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/action/TestSetLinearPriceMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/AbstractConditionMetadataFactoryTest.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/TestCharacteristicConditionMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/TestDateTimeIntervalConditionMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/TestGlobalTableQueryConditionMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/TestTieredAvailableUnitsConditionMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/TestTieredBucketBalanceConditionMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/TestAttributeMetadata.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/TestExternalReferenceMetadata.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/TestInternalReferenceMetadata.java', ';', 'Add reference metadata to attribute metadata  Adds metadata for references to attribute metadata to explain what kind of references are allowed for the attribute', ';', 'nan', ';', '68']
5244
Added:  ['Id9c9184b81c8de4a49ed6630074ef0c646721341', ';', 'src/main/java/com/ericsson/bss/rmca/copilot/internal/erd/tool/ToolHelper.java', ';', 'Fix for incorrect JSON  Try to fix issue with bad JSON', ';', 'nan', ';', '68']
5245
5246
Added:  ['Id9d6e3d1dd9d43027fecc6dabf4b5a475c6247df', ';', 'src/main/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfigurationlistpageservice/predicates/TextPredicate.java;src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/businessconfigurationlistpageservice/predicates/TestTextPredicate.java', ';', 'Improve text search for business data  Improve the text search to also include certain column values which are visually available to the user.  This could be improved further to support even more columns  Tracking-Id: EIP', ';', 'nan', ';', '9255']
5247
Added:  ['Id9e725c69a838a50357ea9593fbad8832d632028', ';', 'src/main/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/TieredRatingConditionMetadataFactory.java;src/test/java/com/ericsson/bss/rmca/validation/rulebuilder/metadata/condition/TestTieredRatingConditionMetadataFactory.java', ';', 'Update metadata for upper limit on tiered rate  Updates metadata for upper limits on tiered rate to optional (0-1) cardinality', ';', 'nan', ';', '68']
5248
5249
5250
Added:  ['Ida56c17c53a6d800da41e92d6151cf4d125382c0', ';', 'src/test/java/com/ericsson/bss/rmca/restserviceimpl/restinternal/pageentities/pages/productoffering/characteristics/test.java;', ';', 'test', ';', 'nan', ';', '8734']
5251
5252
5253
Added:  ['Ida680d4101d4511fb5d79a029aa6163925715d93', ';', 'src/main/java/com/ericsson/bss/rmca/integrationtest/fcsim/RmcaFcDefaults.java;src/test/java/com/ericsson/bss/rmca/integrationtest/testcases/TestFunctionControl_ITCase.java;src/main/java/com/ericsson/bss/rmca/oamservices/fc/definition/RmcaFunctionDefinition.java', ';', 'Add FC for PO price optimization  Adds FC for PO price optimization', ';', 'nan', ';', '68']
5254
5255
Added:  ['Ida937812d57e86e4996348071a57a9a34b3829db', ';', 'src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorCode.java;src/main/java/com/ericsson/bss/rmca/entitymodificationviews/validation/ValidationErrorFactory.java;src/test/java/com/ericsson/bss/rmca/integrationtest/componenttestcases/validation/rules/characteristic/TestRangePurposeCharacteristicValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/CharacteristicPolicyValueRangeValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/RangePurposeCharacteristicValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/AbstractOptimizedConditionValidationRule.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/ConditionValidationContext.java;src/main/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/RangeLimitValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/characteristic/TestCharacteristicPolicyValueRangeValidationRule.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/TestConditionValidationContext.java;src/test/java/com/ericsson/bss/rmca/validation/validation/rules/price/condition/TestRangeLimitValidationRule.java', ';', 'Validate UPPER_LIMIT and LOWER_LIMIT  Based on CharacteristicPolicyValueRangeValidationRule  Validates that LOWER_LIMIT <= UPPER_LIMIT and that both limit attributes have compatible measures.', ';', 'nan', ';', '2591']
5256
5257

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [463]:
PBT_df

,0,1,2,3,4,5,6,7,8
0,I001768f8d53c879f8c826e98d24b0130eef344f1,;,src/main/java/com/ericsson/bss/rmca/entitymodi...,;,Validate condition and action spec references,;,nan,;,2591
1,I006526646bde76663d20e9944cb85c0c0307b4fc,;,src/main/java/com/ericsson/bss/rmca/restservic...,;,Remove dependency to write rmca in restservice...,;,nan,;,810
2,I006d7ae89ce769c61bd737c38178b44e924a5549,;,src/main/java/com/ericsson/bss/rmca/eventservi...,;,Change bcce schema version to 1.7.0 This upda...,;,nan,;,2427
3,I00756af13d2cb517bed558f5d8758d2a4e19e5f4,;,src/main/java/com/ericsson/bss/rmca/restservic...,;,Update POP Creator for internal realation Upd...,;,nan,;,4679
4,I007586521e73a61abce884421a5e85b2f7d42c9b,;,src/main/java/com/ericsson/bss/rmca/cn/fabric8...,;,DUMMY Tracking-Id:,;,nan,;,1530
...,...,...,...,...,...,...,...,...,...
2493,Iffc1095a3e5ce6a544dfd87de12d541dad4c1e58,;,src/main/java/com/ericsson/bss/rmca/validation...,;,Allow for null or empty entity Allow for null...,;,nan,;,9255
2494,Iffc6857272006f1445fa720df661cd9c681c5aef,;,src/main/java/com/ericsson/bss/rmca/restservic...,;,Update catalog integration message body writer...,;,nan,;,68
2495,Iffca17a9ce002e1504a373167f6320126e5b6e58,;,src/main/java/com/ericsson/bss/rmca/entitymodi...,;,Add expired predicate Add the expired predica...,;,nan,;,9255
2496,Iffd80a804135253ae45cd2f8865491f57dd547c2,;,src/main/java/com/ericsson/bss/rmca/persistenc...,;,Revert Update readAllSharedIds This reverts c...,;,nan,;,68
2497,Ifff275a1012ba92bbbb00e6214c64d6f9fbc30a1,;,src/main/java/com/ericsson/bss/rmca/oamservice...,;,Fix target drop Fix target drop Tracking-Id:...,;,nan,;,5080

In [464]:
#convert each line to only containing one file

def create_one_file_lines(commitDF):
    one_line = []
    for row in commitDF.itertuples(index = False):
        pr = row[0]
        files = row[2]
        title = row[4]
        body = row[6]
        author = row[8]
        
        for file in files.split(';'):
            if (not file == ''): #I think somewhere one of the methods is adding a ; at the end
                                 #but this is easier than hunting that problem down
                one_line.append([pr, ';', file, ';', title, ';', body, ';', author])
    
    return pd.DataFrame(one_line)

In [465]:
out_df = create_one_file_lines(PBT_df)

In [466]:
out_df

,0,1,2,3,4,5,6,7,8
0,I001768f8d53c879f8c826e98d24b0130eef344f1,;,src/main/java/com/ericsson/bss/rmca/entitymodi...,;,Validate condition and action spec references,;,nan,;,2591
1,I001768f8d53c879f8c826e98d24b0130eef344f1,;,src/main/java/com/ericsson/bss/rmca/entitymodi...,;,Validate condition and action spec references,;,nan,;,2591
2,I001768f8d53c879f8c826e98d24b0130eef344f1,;,src/main/java/com/ericsson/bss/rmca/validation...,;,Validate condition and action spec references,;,nan,;,2591
3,I001768f8d53c879f8c826e98d24b0130eef344f1,;,src/main/java/com/ericsson/bss/rmca/validation...,;,Validate condition and action spec references,;,nan,;,2591
4,I001768f8d53c879f8c826e98d24b0130eef344f1,;,src/main/java/com/ericsson/bss/rmca/validation...,;,Validate condition and action spec references,;,nan,;,2591
...,...,...,...,...,...,...,...,...,...
33115,Iffca17a9ce002e1504a373167f6320126e5b6e58,;,src/test/java/com/ericsson/bss/rmca/restservic...,;,Add expired predicate Add the expired predica...,;,nan,;,9255
33116,Iffd80a804135253ae45cd2f8865491f57dd547c2,;,src/main/java/com/ericsson/bss/rmca/persistenc...,;,Revert Update readAllSharedIds This reverts c...,;,nan,;,68
33117,Iffd80a804135253ae45cd2f8865491f57dd547c2,;,src/test/java/com/ericsson/bss/rmca/persistenc...,;,Revert Update readAllSharedIds This reverts c...,;,nan,;,68
33118,Ifff275a1012ba92bbbb00e6214c64d6f9fbc30a1,;,src/main/java/com/ericsson/bss/rmca/oamservice...,;,Fix target drop Fix target drop Tracking-Id:...,;,nan,;,5080
33119,Ifff275a1012ba92bbbb00e6214c64d6f9fbc30a1,;,src/main/java/com/ericsson/bss/rmca/oamservice...,;,Fix target drop Fix target drop Tracking-Id:...,;,nan,;,5080

In [467]:
out_df.to_csv('fixed_filesPR3BodyTitle2rmca.csv', encoding='utf-8', header=False, index=False, sep='\t')

In [468]:
import numpy as np
with open('fixed_filesPR3BodyTitle2rmca.txt', 'w', encoding='utf-8') as f:
    np.savetxt(f, out_df.values, fmt='%s', delimiter=' ')